---
title: HMNDLX Site Stack
timezone: Europe/Berlin
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
email: ich@johannesippen.com
description: This is a test & demo of the HMNDLX Site Stack.
baseurl: 
url: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
